# Generated by Django 4.2.2 on 2023-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=30, unique=True, verbose_name='Столица'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(unique=True, verbose_name='Телефонный код'),
        ),
    ]
